version: '3.8'
services:
  sqlserver:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: "password1"
      POSTGRES_USERNAME: "userdb"
      POSTGRES_DB: "userdb"
      POSTGRES_USER: "newuser"
    volumes:
      - ./sql_scripts:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    ports:
      - "3001:3001"
    depends_on:
      - sqlserver
    environment:
      DB_HOST: "sqlserver"
      DB_USER: "newuser"
      DB_PASSWORD: "password1"
      DB_DATABASE: "userdb"
      DB_PORT: "5432"
      PORT: "3001"
      ACCESS_TOKEN_SECRET: "secret"
      CORS_ORIGINS: "http://0.0.0.0:3000"
     
  frontend:
    build: 
      context: ./frontend
      args:
        REACT_APP_DATABASEURL: "http://localhost:3001/api"
    ports:
      - "3000:3000"
    depends_on:
      - backend